#!/bin/sh
## brightness - Brightness control and notification
## Dependencies: brightnessctl dunst
## Author: Thiago Mota (github.com/Thiago4532)

step='5%'

case "$1" in
    'up')
        cmd="$step+"
        ;;
    'down')
        cmd="$step-"
        ;;
    *)
        exit 1
        ;;
esac

brightnessctl -m s $cmd | cut -d',' -f4 |
    xargs -i dunstify -i notification-display-brightness -h string:x-dunst-stack-tag:brightness -t 1000 \
    -u normal "Brightness: {}"
