#!/bin/sh

color=`grabc` || exit $?

# Copy color to clipboard
echo -n $color | xclip -i -selection clipboard

# Create an image of a circle
tmpfile=`mktemp /tmp/cgrab-XXXXXX.png`
convert -size 64x64 xc:"#ffffff00" -fill $color -draw 'circle 32,32 32,62' $tmpfile

# Send notification
notify-send -i $tmpfile Color $color

# Delete tmpfile
unlink $tmpfile
