#!/bin/bash
## download2cache

set -o pipefail

if [[ $# == 0 ]]; then
    echo "usage: download2cache <packages...>" >&2
    exit 1
fi

for pkg in "$@"; do
    if [[ "$pkg" =~ ^- ]]; then
        echo "invalid package: $pkg" >&2
        echo "usage: download2cache <packages...>" >&2
        exit 1
    fi
done

function list_urls() {
    pacman -S --print "$@"
}

PACKAGES=()
CACHE=/var/cache/pacman/pkg

pacman -S --print-format "%n %f" "$@" | while read -r name pkg; do
    letter="${name::1}"
    url="https://archive.archlinux.org/packages/$letter/$name/$pkg"
    echo "Downloading $url"
    sudo curl -O --output-dir "$CACHE" "$url"
    echo "Downloading $url.sig"
    sudo curl -O --output-dir "$CACHE" "$url.sig"
done || exit $?

