#!/bin/bash
## download2cache with aria2c

set -o pipefail

if [[ $# == 0 ]]; then
    echo "usage: download2cache <packages...>" >&2
    exit 1
fi

for pkg in "$@"; do
    if [[ "$pkg" =~ ^- ]]; then
        echo "invalid package: $pkg" >&2
        echo "usage: download2cache <packages...>" >&2
        exit 1
    fi
done

CACHE=/var/cache/pacman/pkg

MAX_CONCURRENT_DOWNLOADS=5
ARIA2C_OPTS="\
    --dir=$CACHE \
    --input-file=- \
    --max-concurrent-downloads=$MAX_CONCURRENT_DOWNLOADS \
    --continue=true \
    --allow-overwrite=false"

# Generate URLs for package files and their signatures
pacman -S --print-format "%n %f" "$@" | while read -r name pkg; do
    letter="${name::1}"
    url="https://archive.archlinux.org/packages/$letter/$name/$pkg"
    echo "$url"
    echo "$url.sig"
done | sudo aria2c $ARIA2C_OPTS || exit $?

