#!/bin/sh

case "$1" in
    'off')
        XRANDR_CMD='xrandr --output eDP-1 --auto --primary --output HDMI-1-0 --off'
        ;;
    'mirror')
        XRANDR_CMD='xrandr --output eDP-1 --auto --primary --output HDMI-1-0 --auto --same-as eDP-1'
        ;;
    *)
        exit 1
        ;;
esac

({
$XRANDR_CMD

sleep 1

## Restart xmonad
xmonad --restart

}&) > /dev/null 2>&1
