#!/bin/sh

SOUND_CHANGE=/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
STEP=5

VOLUME_LOW=15
VOLUME_HIGH=55

volume_notification_send() {
    local notification_icon

    if [ "$2" = "off" ]; then
        notification_icon='notification-audio-volume-muted'
    elif [ $1 -le $VOLUME_LOW ]; then
        notification_icon='notification-audio-volume-low'
    elif [ $1 -lt $VOLUME_HIGH ]; then
        notification_icon='notification-audio-volume-medium'
    else
        notification_icon='notification-audio-volume-high'
    fi

    dunstify -i "$notification_icon" -h string:x-dunst-stack-tag:sound \
        -t 1000 -u normal "Volume: $1%"
}

mode=""

while [ $# -gt 0 ]; do
    case "$1" in
        -s|--step)
            shift
            [ -z "${1##*[!0-9]*}" ] && exit 1
            STEP=$1
            ;;
        *)
            [ -z "$mode" ] && mode="$1" || exit 1
            ;;
    esac
    shift
done

case "$mode" in
    'down')
        cVolume=`amixer sset Master "${STEP}%-,${STEP}%-" |
            grep 'Left:' |
            awk -F'[][]' '{print substr($2, 0, length($2)-1) " " $4}'`

        volume_notification_send $cVolume
        paplay "$SOUND_CHANGE" &
        ;;
    'up')
        cVolume=`amixer sset Master "${STEP}%+,${STEP}%+" |
            grep 'Left:' |
            awk -F'[][]' '{print substr($2, 0, length($2)-1) " " $4}'`

        volume_notification_send $cVolume
        paplay "$SOUND_CHANGE" &
        ;;
    'mute')
        cVolume=`amixer set Master toggle,toggle |
            grep 'Left:' |
            awk -F'[][]' '{print substr($2, 0, length($2)-1) " " $4}'`

        volume_notification_send $cVolume
        ;;
    *)
        exit 1
        ;;
esac
